version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: future-star-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: future_star_center
    volumes:
      - mongodb_data:/data/db
    networks:
      - future-star-network

  # Redis
  redis:
    image: redis:latest
    container_name: future-star-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - future-star-network

  # API Backend
  api:
    build: .
    container_name: future-star-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ENV: production
      PORT: 8080
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/future_star_center?authSource=admin
      MONGODB_DATABASE: future_star_center
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      JWT_SECRET: "your-super-secret-jwt-key-change-this-in-production"
      JWT_EXPIRES_IN: 24h
      SESSION_EXPIRES_IN: 7200s
      PASSWORD_RESET_EXPIRES_IN: 3600s
    depends_on:
      - mongodb
      - redis
    networks:
      - future-star-network

volumes:
  mongodb_data:
  redis_data:

networks:
  future-star-network:
    driver: bridge
